name: Parallel Test Execution

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_index: [1, 2, 3, 4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Run Balanced Tests
        run: |
          ./run-tests.sh schedule.json ${{ matrix.node_index }}
